title = 'Dave Cutting'
baseURL = 'https://davecutting.com/'
languageCode = 'en-us'
theme = 'ananke'

[params]
  author = "Dave Cutting"
  favicon = ""
  site_logo = ""
  description = "Embedded electrical design wizard"
  background_color_class = "bg-dark-gray"
  recent_posts_number = 3

[[params.ananke_socials]]
name = "github"
url = "https://github.com/steezeman"

[[params.ananke_socials]]
name = "linkedin"
url = "https://linkedin.com/in/steezeman"
share = false
